"""Compile a Lua script file into a standalone C header with a const string.

FOR TESTING PURPOSES ONLY.  Reads a .lua file, escapes its contents, and
writes a .h file containing the script as a const char[] wrapped in an
include guard.  Superseded by lua_cat.py + lua_template.h.in for production.
"""

import os
import argparse

argparser = argparse.ArgumentParser(
    description="Convert Lua script files to C const strings."
)
argparser.add_argument("file", type=str, help="Lua script file to convert")
args = argparser.parse_args()

with open(args.file, "r") as f:
    script = f.read()
    strings = []
    for line in script.splitlines():
        line = line.strip()
        line = line.replace('"', '\\"')
        line = line.replace("\n", " ")
        line = line.replace("\r", "")
        line = line.replace("\t", " ")

        strings.append(line)

strings = " ".join(strings)

with open(os.path.splitext(args.file)[0] + ".h", "w") as f:
    script_name = (args.file).replace(".", "_").replace("/", "_")
    var_name = script_name.split("_")[-2] + "_script"

    f.write("/* FILE AUTOGENERATED BY lua_to_h.py */\n")
    f.write("#ifndef ")
    f.write(script_name.upper())
    f.write("\n")
    f.write("#define ")
    f.write(script_name.upper())
    f.write("\n\n")
    f.write("const char " + var_name + '[] = "')
    f.write(strings)
    f.write('";\n\n')
    f.write("#endif /* " + script_name.upper() + "*/\n")
